jobs:
  commitlint:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - continue-on-error: true
      uses: wagoid/commitlint-github-action@v4
      with:
        configFile: ./.commitlintrc.yml
name: Lint Commit Messages
on:
  repository_dispatch:
    types: trigger-ga___pr-commitlint.yml
