jobs:
  build-and-test:
    env:
      DISABLE_TENCENT_MAVEN_MIRROR: true
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v3.x
    - continue-on-error: true
      name: checkout
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        cache: gradle
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties')
          }}
        path: '~/.gradle/caches

          ~/.gradle/wrapper

          '
        restore-keys: '${{ runner.os }}-gradle-

          '
    - continue-on-error: true
      name: revert gradle wrapper mirror setting
      run: echo 'distributionUrl=https\://services.gradle.org/distributions/gradle-7.5-bin.zip'
        >  gradle/wrapper/gradle-wrapper.properties
    - continue-on-error: true
      name: buildSdk
      run: ./gradlew buildSdk
    - continue-on-error: true
      name: build sample/source
      run: ./gradlew build
    - continue-on-error: true
      name: unit test
      run: ./gradlew jvmTestSdk -S
    - continue-on-error: true
      name: run androidTestSdk on API 28 emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 28
        arch: x86_64
        emulator-build: 8420304
        profile: pixel_xl
        script: ./gradlew androidTestSdk
        target: default
    - continue-on-error: true
      name: stop gradle deamon for actions/cache
      run: ./gradlew --stop
  publish:
    env:
      DISABLE_TENCENT_MAVEN_MIRROR: true
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PUBLISH_RELEASE: true
    needs: build-and-test
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v3.x
    - continue-on-error: true
      name: checkout
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        cache: gradle
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties')
          }}
        path: '~/.gradle/caches

          ~/.gradle/wrapper

          '
        restore-keys: '${{ runner.os }}-gradle-

          '
    - continue-on-error: true
      name: revert gradle wrapper mirror setting
      run: echo 'distributionUrl=https\://services.gradle.org/distributions/gradle-7.5-bin.zip'
        >  gradle/wrapper/gradle-wrapper.properties
    - continue-on-error: true
      name: publish
      run: ./gradlew publish
    - continue-on-error: true
      name: stop gradle deamon for actions/cache
      run: ./gradlew --stop
name: Publish release
on:
  repository_dispatch:
    types: trigger-ga___release.yml
